### ISSUE TITLE
Don't work on Minetest 5.2

### ISSUE THREAD

**Issue by AFCMS** [random-geek/meshport#3] opened 2020-05-10 16:42 UTC
When I export a selection, Minetest screen turns gray and don't answer even if I wait a long time.
Nothing is generated.

**Comment by random-geek** [comment] 2020-05-10 23:50
@AFCMS Are there any error messages in your debug.txt? If so, you could post them here.
I suspect I know what the problem is.

**Comment by AFCMS** [comment] 2020-05-11 13:45
This is the log:
2020-05-11 15:42:43: ACTION[Server]: louis [127.0.0.1] joins game. List of players: louis
2020-05-11 15:42:43: WARNING[Server]: 3d_armor: Detached armor inventory is nil [set_player_armor]
2020-05-11 15:43:46: WARNING[Server]: Undeclared global variable "file_exists" accessed at ...etest-5.2.0-win64\bin\..\mods\meshport-master/export.lua:172
2020-05-11 15:43:46: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'meshport' in callback on_chat_message(): ...etest-5.2.0-win64\bin\..\mods\meshport-master/export.lua:172: attempt to call global 'file_exists' (a nil value)
2020-05-11 15:43:46: ERROR[Main]: stack traceback:
2020-05-11 15:43:46: ERROR[Main]: 	...etest-5.2.0-win64\bin\..\mods\meshport-master/export.lua:172: in function 'create_mesh'
2020-05-11 15:43:46: ERROR[Main]: 	...inetest-5.2.0-win64\bin\..\mods\meshport-master\init.lua:73: in function 'func'
2020-05-11 15:43:46: ERROR[Main]: 	...\Louis\minetest-5.2.0-win64\bin\..\builtin\game\chat.lua:69: in function <...\Louis\minetest-5.2.0-win64\bin\..\builtin\game\chat.lua:48>
2020-05-11 15:43:46: ERROR[Main]: 	...is\minetest-5.2.0-win64\bin\..\builtin\game\register.lua:429: in function <...is\minetest-5.2.0-win64\bin\..\builtin\game\register.lua:413>
2020-05-11 15:43:46: ACTION[Server]: louis leaves game. List of players: 
2020-05-11 15:43:46: ACTION[Main]: Server: Shutting down

**Comment by AFCMS** [comment] 2020-05-11 13:45
There is no mobs in the zone.

**Comment by AFCMS** [comment] 2020-05-11 13:46
List of mods ?

**Comment by random-geek** [comment] 2020-05-11 20:38
Fixed by 1dd3aa4.

**Closed by random-geek** 2020-05-11 20:38 UTC
